export const TOKEN_KEY = "pw_access_token";
export const LOGIN_PAGE = "../login/index.html";
export const API_BASE = "http://127.0.0.1:5000";

export const VARIABLE_LABELS = {
  air_temperature: "Temperatura",
  air_humidity: "Umidade",
  air_pressure: "Pressão",
  wind_speed: "Velocidade do vento",
  wind_direction: "Direção do vento",
  rain_accumulated: "Precipitacao acumulada"
};

export const VARIABLE_UNITS = {
  air_temperature: "°C",
  air_humidity: "%",
  air_pressure: "hPa",
  wind_speed: "m/s",
  wind_direction: "°",
  rain_accumulated: "mm"
};

export const refs = {
  error: document.getElementById("dashboard-error"),
  sidebar: document.getElementById("sidebar"),
  sidebarToggleBtn: document.getElementById("sidebar-toggle-btn"),
  sidebarToggleIcon: document.getElementById("sidebar-toggle-icon"),
  breadcrumbText: document.getElementById("breadcrumb-text"),
  pageTitle: document.getElementById("page-title"),
  viewDataBtn: document.getElementById("view-data-btn"),
  viewMapBtn: document.getElementById("view-map-btn"),
  viewRegisterBtn: document.getElementById("view-register-btn"),
  viewDatahubBtn: document.getElementById("view-datahub-btn"),
  viewReportsBtn: document.getElementById("view-reports-btn"),
  viewUsersBtn: document.getElementById("view-users-btn"),
  viewAdminLogsBtn: document.getElementById("view-admin-logs-btn"),
  dataPanel: document.getElementById("data-panel"),
  registerPanel: document.getElementById("register-panel"),
  datahubPanel: document.getElementById("datahub-panel"),
  reportsPanel: document.getElementById("reports-panel"),
  usersPanel: document.getElementById("users-panel"),
  adminLogsPanel: document.getElementById("admin-logs-panel"),
  dataControls: document.getElementById("data-controls"),
  mapControls: document.getElementById("map-controls"),
  registerControls: document.getElementById("register-controls"),
  viewContextText: document.getElementById("view-context-text"),
  stationMeta: document.getElementById("station-meta"),
  mapLayout: document.getElementById("map-layout"),
  stationSelect: document.getElementById("station-select"),
  stationLocationText: document.getElementById("station-location-text"),
  mapPanel: document.getElementById("stations-map-panel"),
  mapContainer: document.getElementById("stations-map"),
  mapInsightPanel: document.getElementById("map-insight-panel"),
  mapInsightName: document.getElementById("map-insight-name"),
  mapInsightCoords: document.getElementById("map-insight-coords"),
  mapInsightLatest: document.getElementById("map-insight-latest"),
  mapStationsList: document.getElementById("map-stations-list"),
  variableSelect: document.getElementById("variable-select"),
  startDate: document.getElementById("start-date"),
  endDate: document.getElementById("end-date"),
  searchBtn: document.getElementById("search-btn"),
  refreshBtn: document.getElementById("refresh-btn"),
  downloadPdfBtn: document.getElementById("download-pdf-btn"),
  logoutBtn: document.getElementById("logout-btn"),
  userMenuBtn: document.getElementById("user-menu-btn"),
  userMenuPanel: document.getElementById("user-menu-panel"),
  chartTitle: document.getElementById("chart-title"),
  chartSubtitle: document.getElementById("chart-subtitle"),
  chartEmptyState: document.getElementById("chart-empty-state"),
  chartCanvas: document.getElementById("observations-chart"),
  reportsStatusMsg: document.getElementById("reports-status-msg"),
  reportsEmptyState: document.getElementById("reports-empty-state"),
  reportsSummaryGrid: document.getElementById("reports-summary-grid"),
  reportsContext: document.getElementById("reports-context"),
  reportsTableBody: document.getElementById("reports-table-body"),
  reportsStationSelect: document.getElementById("reports-station-select"),
  reportsStartDate: document.getElementById("reports-start-date"),
  reportsEndDate: document.getElementById("reports-end-date"),
  reportsApplyBtn: document.getElementById("reports-apply-btn"),
  reportsRefreshBtn: document.getElementById("reports-refresh-btn"),
  reportsDownloadBtn: document.getElementById("reports-download-btn"),
  datahubIngestTarget: document.getElementById("datahub-ingest-target"),
  datahubIngestFile: document.getElementById("datahub-ingest-file"),
  datahubIngestBtn: document.getElementById("datahub-ingest-btn"),
  datahubIngestMsg: document.getElementById("datahub-ingest-msg"),
  datahubPreviewBox: document.getElementById("datahub-preview-box"),
  datahubPreviewSummary: document.getElementById("datahub-preview-summary"),
  datahubPreviewHead: document.getElementById("datahub-preview-head"),
  datahubPreviewBody: document.getElementById("datahub-preview-body"),
  datahubExportTable: document.getElementById("datahub-export-table"),
  datahubExportFormat: document.getElementById("datahub-export-format"),
  datahubExportBtn: document.getElementById("datahub-export-btn"),
  datahubExportMsg: document.getElementById("datahub-export-msg"),
  summaryGrid: document.getElementById("summary-grid"),
  previewMapContainer: document.getElementById("station-preview-map"),
  previewMapEmpty: document.getElementById("station-preview-empty"),
  latestTableBody: document.getElementById("latest-table-body"),
  registerDeviceForm: document.getElementById("register-device-form"),
  registerDeviceName: document.getElementById("register-device-name"),
  registerDeviceMsg: document.getElementById("register-device-msg"),
  registerLocationForm: document.getElementById("register-location-form"),
  registerLocationDevice: document.getElementById("register-location-device"),
  registerLocationLat: document.getElementById("register-location-lat"),
  registerLocationLon: document.getElementById("register-location-lon"),
  registerLocationMsg: document.getElementById("register-location-msg"),
  registerUserForm: document.getElementById("register-user-form"),
  registerUserName: document.getElementById("register-user-name"),
  registerUserEmail: document.getElementById("register-user-email"),
  registerUserPassword: document.getElementById("register-user-password"),
  registerUserMsg: document.getElementById("register-user-msg"),
  usersTableBody: document.getElementById("users-table-body"),
  usersStatusMsg: document.getElementById("users-status-msg"),
  adminLogsStartDate: document.getElementById("admin-logs-start-date"),
  adminLogsEndDate: document.getElementById("admin-logs-end-date"),
  adminLogsUserFilter: document.getElementById("admin-logs-user-filter"),
  downloadLogsBtn: document.getElementById("download-logs-btn"),
  adminLogsMsg: document.getElementById("admin-logs-msg")
};

export const state = {
  devices: [],
  chart: null,
  locationByDeviceId: {},
  map: null,
  mapMarkersLayer: null,
  previewMap: null,
  previewMarker: null,
  latestObservationByDeviceId: {},
  markerByDeviceId: {},
  currentObservations: [],
  currentSeriesQuery: null,
  lastSeriesSignature: "",
  currentReportSignature: "",
  currentReportData: [],
  currentReportLoading: false,
  currentReportFilters: {
    stationId: "all",
    start: "",
    end: ""
  },
  lastUsersSignature: "",
  lastMapSignature: "",
  usersAutoRefreshInFlight: false,
  reportsAutoRefreshInFlight: false,
  seriesAutoRefreshTimer: null,
  seriesAutoRefreshInFlight: false,
  currentUser: null,
  currentUserClientId: null,
  currentUserIsAdmin: false
};
